Fix travis bundler failures
Currently a good portion of our builds are failing due to the following error

    NoMethodError: undefined method `spec' for nil:NilClass

Fix found here:
https://github.com/travis-ci/travis-ci/issues/5239#issuecomment-167355686